name: whats_link_generator
description: "A link generator for the green chatting app."
publish_to: 'none' 


version: 1.0.0+4

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl_phone_field: ^3.2.0
  url_launcher: ^6.3.1
  provider: ^6.1.2
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: "^0.14.4"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"

flutter:

  uses-material-design: true